POST http://localhost:3333/api/product
Content-Type: application/json

{
  "name": "Test",
  "price": 36.83,
  "inventory": 2,
  "sku": "0591-asdfasdf"
}

###
# curl --location --request PATCH 'http://localhost:3333/api/product/64942-1096'
#--header 'Content-Type: application/json'
#--data-raw '{
#    "price": 1.17
#}'
PATCH http://localhost:3333/api/product/37808-177
Content-Type: application/json

{
    "price": 5.00
}
###

GET http://localhost:3333/api/product
Accept: application/json
###

# curl -X 'GET'
#  'http://localhost:3333/product'
#  -H 'accept: */*'
GET http://localhost:3333/api/product
accept: */*

###

GET http://localhost:3333/api/product/0591-3973
Accept: application/json
###

DELETE http://localhost:3333/api/product/0591-3973
Accept: application/json
###








